language: node_js
nodejs: 8
before_install:
  - if [ ! -z "$SSH_KEY" ]; then echo $SSH_KEY | base64 --decode > $HOME/.ssh/id_rsa; fi
  - chmod 600 $HOME/.ssh/id_rsa
install:
  - npm install
  - npm run build
script:
  - true
deploy:
  provider: script
  skip_cleanup: true
  script : rsync -r --delete-after --quiet -e "ssh -o StrictHostKeyChecking=no" $TRAVIS_BUILD_DIR/dist $SSH_USER@$SERVER_IP:$DEPLOY_PATH
  on:
    branch: master
cache:
  directories:
   - "node_modules"
